version: '3.8'
services:
    db:
        container_name: db-web
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456 
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '9000:80'
      environment:
          PMA_HOST: db
      depends_on:
          - db

